parameters:
  happyr.google.analytics.tracker.class: 'Happyr\Google\AnalyticsBundle\Service\Tracker'
  happyr.google.analytics.http.client.class: 'Happyr\Google\AnalyticsBundle\Http\HttpClient'
  happyr.google.analytics.http.dummy.class: 'Happyr\Google\AnalyticsBundle\Http\Dummy'

services:
  happyr.google.analytics.tracker:
    class: %happyr.google.analytics.tracker.class%
    arguments: [@happyr.google.analytics.http.client, ~, ~]

  happyr.google.analytics.http.client:
    class: %happyr.google.analytics.http.client.class%
    arguments: [~]

  happyr.google.analytics.http.dummy:
    class: %happyr.google.analytics.http.dummy.class%
    arguments: []
