
services:
  Happyr\GoogleAnalyticsBundle\Service\Tracker:
    arguments: ['@Happyr\GoogleAnalyticsBundle\Http\AnalyticsClientInterface', '@Happyr\GoogleAnalyticsBundle\Service\ClientIdProvider', ~, ~]

  Happyr\GoogleAnalyticsBundle\Http\VoidHttpClient: ~

  Happyr\GoogleAnalyticsBundle\Service\ClientIdProvider:
    arguments: ["@request_stack"]
