parameters:



services:
  happyr.google.analytics.page_statistics:
    class: HappyR\Google\AnalyticsBundle\Services\PageStatisticsService
    arguments: [@happyr.google.api.analytics, @happyr.google.analytics.token, @cache, %happy_r_google_analytics%]

  happyr.google.analytics.token:
    class: HappyR\Google\AnalyticsBundle\Services\TokenService
    arguments: [%happy_r_google_analytics.token_file_path%]
