language: php
sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
  - SYMFONY_VERSION=2.8.*

cache:
    directories:
        - $HOME/.composer/cache/files

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - phpunit

matrix:
  include:
    - env: SYMFONY_VERSION=3.1.*
      php: 7.1
    - env: SYMFONY_VERSION=3.0.*
      php: 7.1
    - env: SYMFONY_VERSION=2.7.*
      php: 7.1
