language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source

script: phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master




