language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*


sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - phpunit
