language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  except:
    - /^analysis-.*$/

env:
  global:
    - TEST_COMMAND="composer test"
    - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
    - env: SYMFONY_VERSION=3.1.*
      php: 7.1
    - env: SYMFONY_VERSION=3.0.*
      php: 7.1
    - env: SYMFONY_VERSION=2.7.*
      php: 7.1
    - env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci" SYMFONY_VERSION=2.7.*
      php: 5.5

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - $TEST_COMMAND

after_success:
  - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
