language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
  - SYMFONY_VERSION=2.3.*

install:
  - composer require --no-update satooshi/php-coveralls:~0.6@stable
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer update

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master