language: php
sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - travis_retry composer self-update

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - phpunit

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=3.0.*
    - php: 5.4
