<?php

namespace HappyR\Google\AnalyticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoogleApiReportTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoogleApiReportTokenRepository extends EntityRepository
{

    public function findOne()
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT e FROM HappyRGoogleAnalyticsBundle:GoogleApiReportToken e'
            )->setMaxResults(1);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
